FROM golang:1.9 as build
WORKDIR /go/src/envbin
COPY . .
RUN go-wrapper download # go get -d -v ./...
ENV CGO_ENABLED=0
RUN go-wrapper install # go install -v ./...

FROM ubuntu:17.10
RUN apt-get update \
    && apt-get install -y \
        virt-what \
    && rm -rf /var/lib/apt/lists/*
COPY --from=build /go/bin/envbin /
COPY --from=build /go/src/envbin/main.html /

EXPOSE 8080
CMD ["/envbin"]
